"""Add waste_records to qa_inspections

Revision ID: 0179f5fad5a6
Revises: c640918e00b7
Create Date: 2026-07-10 17:02:00.629217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0179f5fad5a6'
down_revision: Union[str, Sequence[str], None] = 'c640918e00b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bravo_qa_inspections', sa.Column('waste_records', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bravo_qa_inspections', 'waste_records')
    # ### end Alembic commands ###
