"""add_machine_maintenance_fields

Revision ID: 44cd3439f2da
Revises: 544d60e5ad24
Create Date: 2026-07-07 23:56:36.640426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cd3439f2da'
down_revision: Union[str, Sequence[str], None] = '544d60e5ad24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bravo_machines', sa.Column('last_maintenance_date', sa.DateTime(), nullable=True))
    op.add_column('bravo_machines', sa.Column('maintenance_comments', sa.Text(), nullable=True))
    op.add_column('bravo_machines', sa.Column('maintenance_incidents', sa.Text(), nullable=True))
    op.add_column('bravo_machines', sa.Column('needs_supplies', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # Check if 'warranty_days' column already exists in 'repairs'
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('repairs')]
    if 'warranty_days' not in columns:
        op.add_column('repairs', sa.Column('warranty_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repairs', 'warranty_days')
    op.drop_column('bravo_machines', 'needs_supplies')
    op.drop_column('bravo_machines', 'maintenance_incidents')
    op.drop_column('bravo_machines', 'maintenance_comments')
    op.drop_column('bravo_machines', 'last_maintenance_date')
    # ### end Alembic commands ###
