"""add_barcode_to_inventory

Revision ID: 555bdc762810
Revises: df9127c31721
Create Date: 2026-07-02 13:52:33.617573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555bdc762810'
down_revision: Union[str, Sequence[str], None] = 'df9127c31721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'inventory', ['barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_column('inventory', 'barcode')
    # ### end Alembic commands ###
