"""add_system_to_web_config

Revision ID: 80e4e5497480
Revises: d96e4cda222c
Create Date: 2026-06-30 13:29:43.965015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e4e5497480'
down_revision: Union[str, Sequence[str], None] = 'd96e4cda222c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_config', sa.Column('system', sa.String(length=20), server_default='nova', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_config', 'system')
    # ### end Alembic commands ###
