"""add_mockup_file_url

Revision ID: c640918e00b7
Revises: 9e89b4332806
Create Date: 2026-07-10 16:17:38.768883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c640918e00b7'
down_revision: Union[str, Sequence[str], None] = '9e89b4332806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repairs', sa.Column('mockup_file_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repairs', 'mockup_file_url')
    # ### end Alembic commands ###
