"""add_image_url_to_inventory

Revision ID: cb2af3574a45
Revises: 5e04c544ec1d
Create Date: 2026-06-27 12:34:58.450813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2af3574a45'
down_revision: Union[str, Sequence[str], None] = '5e04c544ec1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'image_url')
    # ### end Alembic commands ###
