"""add_bravo_blueprint

Revision ID: d0f22dfb8f50
Revises: 87697178e62c
Create Date: 2026-07-01 00:04:08.483050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0f22dfb8f50'
down_revision: Union[str, Sequence[str], None] = '87697178e62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bravo_machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'INACTIVE', name='machinestatus'), nullable=False),
    sa.Column('system', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bravo_machines_system'), 'bravo_machines', ['system'], unique=False)
    op.create_table('bravo_brand_kits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('typographies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guidelines', sa.String(length=500), nullable=True),
    sa.Column('system', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bravo_brand_kits_client_id'), 'bravo_brand_kits', ['client_id'], unique=False)
    op.create_index(op.f('ix_bravo_brand_kits_system'), 'bravo_brand_kits', ['system'], unique=False)
    op.create_table('bravo_machine_reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('system', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['bravo_machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['repairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bravo_machine_reservations_system'), 'bravo_machine_reservations', ['system'], unique=False)
    op.create_index('ix_reservation_time', 'bravo_machine_reservations', ['start_time', 'end_time'], unique=False)
    op.create_table('bravo_qa_inspections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('inspected_at', sa.DateTime(), nullable=False),
    sa.Column('checklist_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('system', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['repairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_bravo_qa_inspections_system'), 'bravo_qa_inspections', ['system'], unique=False)
    op.add_column('repairs', sa.Column('parent_order_id', sa.Integer(), nullable=True))
    op.add_column('repairs', sa.Column('is_split_child', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_foreign_key(None, 'repairs', 'repairs', ['parent_order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repairs', type_='foreignkey')
    op.drop_column('repairs', 'is_split_child')
    op.drop_column('repairs', 'parent_order_id')
    op.drop_index(op.f('ix_bravo_qa_inspections_system'), table_name='bravo_qa_inspections')
    op.drop_table('bravo_qa_inspections')
    op.drop_index('ix_reservation_time', table_name='bravo_machine_reservations')
    op.drop_index(op.f('ix_bravo_machine_reservations_system'), table_name='bravo_machine_reservations')
    op.drop_table('bravo_machine_reservations')
    op.drop_index(op.f('ix_bravo_brand_kits_system'), table_name='bravo_brand_kits')
    op.drop_index(op.f('ix_bravo_brand_kits_client_id'), table_name='bravo_brand_kits')
    op.drop_table('bravo_brand_kits')
    op.drop_index(op.f('ix_bravo_machines_system'), table_name='bravo_machines')
    op.drop_table('bravo_machines')
    # ### end Alembic commands ###
