"""add quality to screen prices

Revision ID: df9127c31721
Revises: d0f22dfb8f50
Create Date: 2026-07-02 13:06:24.677244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9127c31721'
down_revision: Union[str, Sequence[str], None] = 'd0f22dfb8f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screen_prices', sa.Column('quality', sa.String(length=50), server_default='Original', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screen_prices', 'quality')
    # ### end Alembic commands ###
