"""add rut city to clients

Revision ID: e893cdf754d3
Revises: 5673dfa8a723
Create Date: 2026-06-10 22:06:12.978160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e893cdf754d3'
down_revision: Union[str, Sequence[str], None] = '5673dfa8a723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('rut', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('region', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'clients', ['rut'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'region')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'rut')
    # ### end Alembic commands ###
