"""add_payment_methods

Revision ID: ebf15c34ec39
Revises: a05cf5a0eb9e
Create Date: 2026-06-27 12:06:24.032853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebf15c34ec39'
down_revision: Union[str, Sequence[str], None] = 'a05cf5a0eb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repairs', sa.Column('deposit_payment_method', sa.String(length=50), nullable=True))
    op.add_column('repairs', sa.Column('final_payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repairs', 'final_payment_method')
    op.drop_column('repairs', 'deposit_payment_method')
    # ### end Alembic commands ###
